version: "3.7"

services:
  vscode:
    build: .
    image: elixir
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      # Git config
      # - ~/.gitconfig:/home/districter/.gitconfig
      # - ~/.gitconfig:/root/.gitconfig
      # Kubernetes
      # - ~/.kube:/home/districter/.kube
      # - ~/.kube:/root/.kube
    environment:
      - TZ=
      - MIX_ENV=dev
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app_dev
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
    entrypoint: bash -c "while sleep 1000; do :; done"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: